# YOLOv8-Pose 配置文件
# COCO格式17个人体关键点定义和骨骼连接关系

# 关键点定义
keypoints:
  names:
    - nose            # 0: 鼻子
    - left_eye        # 1: 左眼
    - right_eye       # 2: 右眼
    - left_ear        # 3: 左耳
    - right_ear       # 4: 右耳
    - left_shoulder   # 5: 左肩
    - right_shoulder  # 6: 右肩
    - left_elbow      # 7: 左肘
    - right_elbow     # 8: 右肘
    - left_wrist      # 9: 左手腕
    - right_wrist     # 10: 右手腕
    - left_hip        # 11: 左髋
    - right_hip       # 12: 右髋
    - left_knee       # 13: 左膝
    - right_knee      # 14: 右膝
    - left_ankle      # 15: 左脚踝
    - right_ankle     # 16: 右脚踝

  # 所有连接的列表（用于统一处理）
  all_connections:
    # 脸部/头部
    - [0, 1]
    - [0, 2]
    - [1, 3]
    - [2, 4]
    # 躯干
    - [5, 6]
    - [5, 11]
    - [6, 12]
    - [11, 12]
    # 左臂
    - [5, 7]
    - [7, 9]
    # 右臂
    - [6, 8]
    - [8, 10]
    # 左腿
    - [11, 13]
    - [13, 15]
    # 右腿
    - [12, 14]
    - [14, 16]
